theme = "monokai_pro_spectrum"

[editor]
mouse = false
true-color = true
line-number = "relative"
idle-timeout = 0
completion-trigger-len = 1
cursorline = true
middle-click-paste = false
auto-save = true
bufferline = "multiple"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
snippets = false

[editor.file-picker]
hidden = false

