require('plugins.languages.cpp')
require('plugins.languages.css')
require('plugins.languages.dotnet')
require('plugins.languages.flutter')
require('plugins.languages.go')
require('plugins.languages.html')
require('plugins.languages.python')
require('plugins.languages.rust')
require('plugins.languages.scala')
require('plugins.languages.typescript')
require('plugins.languages.zig')

